---
title: Ракета летить у космос
hero_image: images/banner.png
description: Створи анімацію польоту ракети, яка виводить супутник на орбіту
meta_title: Проєкти з кодування для дітей і підлітків | Ракета летить у космос
meta_description: Вивчай Python за допомогою проєктів з програмування Raspberry Pi Foundation для дітей і підлітків. Зроби анімацію, на якій ракета виводить супутник на орбіту.
version: 0.0.1
listed: true
copyedit: true
last_tested: "2024-10-21"
steps:
  - title: Що ти зробиш
  - title: Намалюй фон
    completion:
      - engaged
  - title: Зліт!
  - title: Ефекти вихлопних газів
    completion:
      - internal
  - title: Швидкий тест
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Додаткове завдання
    challenge: true