---
title: Raket lancering
hero_image: images/banner.png
description: Maak een animatie van een raket die een satelliet in een baan om de aarde brengt
meta_title: Python programmeer projecten voor kinderen en tieners | Raket lancering
meta_description: Leer Python met de codeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Maak een Python-animatie waarin een raket een satelliet in een baan om de aarde lanceert.
version: 0.0.1
listed: true
copyedit: true
last_tested: "2024-10-21"
steps:
  - title: Wat ga je maken
  - title: Teken achtergrond
    completion:
      - engaged
  - title: Lancering!
  - title: Uitlaat effecten
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Uitdaging
    challenge: true
  - title: Wat kun je verder nog doen?
