---
title: Rocket launch
hero_image: images/banner.png
description: Make an animation of a rocket propelling a satellite into orbit
version: 0.0.1
listed: true
copyedit: true
last_tested: "06.10.2021"
steps:
  - 
    title: You will make
  - 
    title: Set the scene
  - 
    title: Liftoff!
    completion:
      - engaged
  - 
    title: Exhaust effects
  - 
    title: Burn fuel
  - 
    title: Reaching orbit
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Улучшение своего проекта
  - 
    title: Что дальше?
