---
title: Lanzamiento de cohete
hero_image: images/banner.png
description: Haz una animación de un cohete que impulsa un satélite a la órbita
meta_title: Proyectos de codificación Python para niños y adolescentes | Lanzamiento de cohete
meta_description: Aprende Python con los proyectos de codificación de la Fundación Raspberry Pi para niños y adolescentes. Haz una animación con Python que muestra un cohete lanzando un satélite a la órbita.
version: 0.0.1
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Lo que harás
  - 
    title: Establece la escena
  - 
    title: '¡El despegue!'
    completion:
      - engaged
  - 
    title: Efectos de escape
  - 
    title: Quemar combustible
  - 
    title: Alcanzando la órbita
    completion:
      - internal
  - 
    title: Prueba Rapida
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: '¿Qué sigue?'
