---
title: Lansio roced
hero_image: images/banner.png
description: Gwnewch animeiddiad o roced yn gyrru lloeren i orbit
meta_title: Python coding projects for kids and teens | Rocket launch
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Python animation that shows a rocket launching a satellite into orbit.
version: 0.0.1
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Cyflwyniad
  - 
    title: Gosod yr olygfa
  - 
    title: Ffwrdd â ni!
    completion:
      - engaged
  - 
    title: Effeithiau'r ecsôst
  - 
    title: Llosgi tanwydd
  - 
    title: Cyrraedd orbit
    completion:
      - internal
  - 
    title: Myfyrio
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Uwchraddio eich brosiect
  - 
    title: Beth nesaf?
