---
title: Lançamento do foguete
hero_image: images/banner.png
description: Faça uma animação de um foguete colocando um satélite em órbita
meta_title: Projetos de codificação Python para crianças e adolescentes | Lançamento do foguete
meta_description: Aprenda Python com os projetos de codificação da Raspberry Pi Foundation para crianças e adolescentes. Faça uma animação Python que mostre um foguete lançando um satélite em órbita.
version: 0.0.1
listed: true
copyedit: true
last_tested: "2024-10-21"
steps:
  - 
    title: What you will make
  - 
    title: Draw the background
    completion:
      - engaged
  - 
    title: Decolar!
  - 
    title: Efeitos da combustão
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?
