---
title: Wystrzelenie rakiety
hero_image: images/banner.png
description: Stwórz animację rakiety napędzającej satelitę na orbitę
meta_title: Projekty kodowania w Pythonie dla dzieci i młodzieży | Rocket launch
meta_description: Naucz się języka Python z projektami programistycznymi Fundacji Raspberry Pi dla dzieci i młodzieży. Stwórz animację w Pythonie, która pokazuje rakietę wystrzeliwującą satelitę na orbitę.
version: 0.0.1
listed: true
copyedit: true
last_tested: "2024-10-21"
steps:
  - 
    title: What you will make
  - 
    title: Draw the background
    completion:
      - engaged
  - 
    title: Startuj!
  - 
    title: Efekty wydechu
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?
