---
title: Lancement de fusée
hero_image: images/banner.png
description: Fais une animation d'une fusée propulsant un satellite en orbite
meta_title: Projets de codage Python pour enfants et adolescents | Lancement de fusée
meta_description: Apprends Python avec les projets de codage de la Raspberry Pi Foundation pour les enfants et les adolescents. Crée une animation Python qui montre une fusée lançant un satellite en orbite.
version: 0.0.1
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Dessiner l'arrière-plan
    completion:
      - engaged
  - 
    title: Décollage !
  - 
    title: Effets d'échappement
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Défi
    challenge: true
  - 
    title: Que peux-tu faire maintenant ?
