---
title: Lancement de fusée
hero_image: images/banner.png
description: Faire une animation d'une fusée propulsant un satellite en orbite
meta_title: Projets de codage Python pour enfants et adolescents | Lancement de fusée
meta_description: Apprendre Python avec les projets de codage de la Raspberry Pi Foundation pour les enfants et les adolescents. Créer une animation Python qui montre une fusée lançant un satellite en orbite.
version: 0.0.1
listed: true
copyedit: true
last_tested: "2024-10-21"
steps:
  - 
    title: What you will make
  - 
    title: Draw the background
    completion:
      - engaged
  - 
    title: Décollage !
  - 
    title: Effets d'échappement
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?
