---
title: Lancement de fusée
hero_image: images/banner.png
description: Faire une animation d'une fusée propulsant un satellite en orbite
version: 0.0.1
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: Créer la scène
  - 
    title: Décollage !
    completion:
      - engaged
  - 
    title: Effets d'échappement
  - 
    title: Brûler du carburant
  - 
    title: Atteindre l'orbite
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
